site_name: Livre Coding üßë‚Äçüíª - Pierre-Etienne
site_url: https://petoulemonde.github.io/livre_coding
site_description: Mon livre de coding - Pierre-Etienne Toulemonde


repo_url: https://github.com/petoulemonde/livre_coding
repo_name: petoulemonde/livre_coding

nav:
  - Homepage: "index.md"
  - Comprendre: 
    - "Comprendre le vibe coding": "Vibe Coding la derni√®re couche d'abstraction en programmation.md"
    - "Place de la blockchain en sant√©": "La blockchain en sant√©.md"
    - "Documentation 2.0": "Documentation 2.0.md"
  - Apprendre:
    - "Libert√© num√©rique": "L'importance de la libert√© num√©rique.md"
    - Windows:
      - "Scoop": "Scoop un gestionnaire de logiciel Windows tr√®s utile - article.md"
    - Le CLI:
      - "Pourquoi apprendre √† coder ?": "Pourquoi apprendre √† coder.md"
      - "Apprivoisez votre terminal": "Apprivoisez votre terminal - article.md"
      - "Votre premier voyage de classe au pays dy CLI": "Votre premier voyage de classe au pays du CLI - blog.md"
    - Python:
      - "Les Pandas plots backends": "The Power of Pandas Plots Backends - article.md"
      - "Master the Python's documentation to make it an ally - article.md"
  - Communiquer:
    - "Cr√©er mon portfolio avec GitHub Pages": "Full Guide to Building a Professional Portfolio with Python, Markdown, Git, and GitHub Pages - article.md"
    - "Cr√©er des pages guthub dynamiques avec Panel": "Dynamic GitHub Pages - Panel (pyodide-worker) - article.md"
  - Economie de la technologie:
    - "Article - Mod√®le √©conomique des sites web et impact informationnelle.md"

theme:
  name: material
  logo: assets/intelligence-artificielle.png
  favicon: assets/intelligence-artificielle.png
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.path
    - navigation.expand
    - navigation.sections
    - navigation.tabs

plugins: 
  - rss